lib/rxsugar:
  :type: git
  :repository: git://github.com/papyri/xsugar.git
  :revision: rails-3-nfd

data/xslt/epidoc:
  :type: subversion
  :repository: https://github.com/EpiDoc/Stylesheets.git
  :revision: 242 

data/xslt/pn/navigator:
  :type: git
  :repository: git://github.com/papyri/navigator.git
  :revision: c03dd1a2a21ca2cfe72eb0b2cc4306a02db5b4fa
