version: "2.2"
services:
  httpd:
    build: apache
    links:
    - "tomcat-sosol"
    - "tomcat-pn"
    - "xsugar"
    - "fuseki"
    - "solr"
    volumes:
    - repo:/srv
    ports:
    - "8000:80"
    depends_on:
      indexer:
        condition: service_healthy
      tomcat-sosol:
        condition: service_started
  sosol:
    build: sosol
    # ports:
    # - "3000:3000"
    volumes:
    - repo:/srv
    links:
    - "xsugar"
    - "mysql"
    depends_on:
      mysql:
        condition: service_started
      repo_clone:
        condition: service_started
      xsugar:
        condition: service_healthy
  repo_clone:
    build: repo_clone
    volumes:
    - repo:/srv
  xsugar:
    build: xsugar
    # ports:
    # - "9999:9999"
    volumes:
    - maven:/root/.m2
  navigator:
    build: navigator
    depends_on:
      repo_clone:
        condition: service_started
      fuseki:
        condition: service_started
    volumes:
    - repo:/srv
    - maven:/root/.m2
    - solr_data:/solr
    links:
    - "fuseki"
  indexer:
    build: indexer
    depends_on:
      navigator:
        condition: service_healthy
      fuseki:
        condition: service_started
      solr:
        condition: service_started
    volumes:
    - repo:/srv
    - maven:/root/.m2
    links:
    - "fuseki"
    - "solr"
    cap_add:
    - SYS_PTRACE
    security_opt:
    - apparmor:unconfined
  fuseki:
    image: ryanfb/fuseki
    volumes:
    - repo:/srv
    - fuseki_data:/data
    mem_limit: '17179869184'
    cpu_count: 2
    environment:
    - OPTS=--port=8090 --tdb2 --loc=/data --update /pi
    - JVM_ARGS=-Xmx8192M
    - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
    ports:
    - "8090:8090"
  mysql:
    image: mysql:5.6
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_USER=pn
    - MYSQL_PASSWORD=p4pyr!
    volumes:
    - ./mysql:/docker-entrypoint-initdb.d
    - mysql_data:/var/lib/mysql
  tomcat-sosol:
    build: tomcat-sosol
    links:
    - "mysql"
    - "xsugar"
    volumes:
    - repo:/srv
    depends_on:
      sosol:
        condition: service_healthy
  solr:
    image: solr:7
    ports:
    - "8983:8983"
    volumes:
    - solr_data:/opt/solr/server/solr
    environment:
    - SOLR_JAVA_MEM=-Xms1G -Xmx8G
    depends_on:
      navigator:
        condition: service_healthy
  tomcat-pn:
    build: tomcat-pn
    links:
    - "mysql"
    - "fuseki"
    ports:
    - "8080:8080"
    volumes:
    - repo:/srv
    depends_on:
      navigator:
        condition: service_healthy
volumes:
  repo:
  maven:
  mysql_data:
  fuseki_data:
  solr_data:
