version: "2.2"
services:
  httpd:
    build: apache
    links:
    - "tomcat-sosol"
    - "xsugar"
    - "fuseki"
    - "solr"
    volumes:
    - repo:/srv
    ports:
    - "8000:80"
  sosol:
    build: sosol
    # ports:
    # - "3000:3000"
    volumes:
    - repo:/srv
    links:
    - "xsugar"
    - "mysql"
    depends_on:
      mysql:
        condition: service_started
      repo_clone:
        condition: service_healthy
      xsugar:
        condition: service_healthy
  repo_clone:
    build: repo_clone
    volumes:
    - repo:/srv
  xsugar:
    build: xsugar
    # ports:
    # - "9999:9999"
    volumes:
    - maven:/root/.m2
  navigator:
    build: navigator
    depends_on:
      repo_clone:
        condition: service_healthy
      fuseki:
        condition: service_started
    volumes:
    - repo:/srv
    - maven:/root/.m2
    links:
    - "fuseki"
  indexer:
    build: indexer
    depends_on:
      navigator:
        condition: service_healthy
      fuseki:
        condition: service_started
    volumes:
    - repo:/srv
    - maven:/root/.m2
    links:
    - "fuseki"
    - "solr"
  fuseki:
    image: ryanfb/fuseki
    volumes:
    - repo:/srv
    environment:
    - OPTS=--loc=/data --update --port=8090 /pi
    - JVM_ARGS=-Xmx4096M
    - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
    # ports:
    # - "8090:8090"
  mysql:
    image: mysql
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_USER=pn
    - MYSQL_PASSWORD=p4pyr!
    volumes:
    - ./mysql:/docker-entrypoint-initdb.d
  tomcat-sosol:
    build: tomcat-sosol
    links:
    - "mysql"
    - "xsugar"
    volumes:
    - repo:/srv
    depends_on:
      sosol:
        condition: service_healthy
  solr:
    build: tomcat-solr
    links:
    - "mysql"
    - "fuseki"
    ports:
    - "8080:8080"
    volumes:
    - repo:/srv
    depends_on:
      navigator:
        condition: service_healthy
volumes:
  repo:
  maven:
