version: "2.2"
services:
  sosol:
    build: sosol
    # ports:
    # - "3000:3000"
    volumes:
    - repo:/srv
    links:
    - "xsugar"
    depends_on:
      repo_clone:
        condition: service_healthy
      xsugar:
        condition: service_healthy
  repo_clone:
    build: repo_clone
    volumes:
    - repo:/srv
  xsugar:
    build: xsugar
    # ports:
    # - "9999:9999"
    volumes:
    - maven:/root/.m2
  navigator:
    build: navigator
    depends_on:
      repo_clone:
        condition: service_healthy
      fuseki:
        condition: service_started
    volumes:
    - repo:/srv
    - maven:/root/.m2
    links:
    - "fuseki"
  indexer:
    build: indexer
    depends_on:
      navigator:
        condition: service_healthy
      fuseki:
        condition: service_started
    volumes:
    - repo:/srv
    - maven:/root/.m2
    links:
    - "fuseki"
    - "solr"
  fuseki:
    image: ryanfb/fuseki
    environment:
    - OPTS=--loc=/data --update --port=8090 /pi
    - JVM_ARGS=-Xmx4096M
    - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
    # ports:
    # - "8090:8090"
  solr:
    build: tomcat-solr
    # ports:
    # - "8080:8080"
    volumes:
    - repo:/srv
    depends_on:
      navigator:
        condition: service_healthy
volumes:
  repo:
  maven:
